const words = [
  {categoryMalayalam:"ഭക്ഷണം",categoryEnglish:"Food",normal:"ബിരിയാണി / Biriyani"},
  {categoryMalayalam:"ഭക്ഷണം",categoryEnglish:"Food",normal:"ദോശ / Dosa"},
  {categoryMalayalam:"ഭക്ഷണം",categoryEnglish:"Food",normal:"പുട്ട് / Puttu"},
  {categoryMalayalam:"ഭക്ഷണം",categoryEnglish:"Food",normal:"അപ്പം / Appam"},
  {categoryMalayalam:"ഭക്ഷണം",categoryEnglish:"Food",normal:"പൊറോട്ട / Porotta"},
  {categoryMalayalam:"ഭക്ഷണം",categoryEnglish:"Food",normal:"ഇഡ്ലി / Idli"},
  {categoryMalayalam:"ഭക്ഷണം",categoryEnglish:"Food",normal:"വട / Vada"},
  {categoryMalayalam:"ഭക്ഷണം",categoryEnglish:"Food",normal:"പായസം / Payasam"},
  {categoryMalayalam:"ഭക്ഷണം",categoryEnglish:"Food",normal:"സമോസ / Samosa"},
  {categoryMalayalam:"ഭക്ഷണം",categoryEnglish:"Food",normal:"ചപ്പാത്തി / Chapati"},

  {categoryMalayalam:"മൃഗങ്ങൾ",categoryEnglish:"Animals",normal:"ആന / Elephant"},
  {categoryMalayalam:"മൃഗങ്ങൾ",categoryEnglish:"Animals",normal:"കടുവ / Tiger"},
  {categoryMalayalam:"മൃഗങ്ങൾ",categoryEnglish:"Animals",normal:"സിംഹം / Lion"},
  {categoryMalayalam:"മൃഗങ്ങൾ",categoryEnglish:"Animals",normal:"നായ / Dog"},
  {categoryMalayalam:"മൃഗങ്ങൾ",categoryEnglish:"Animals",normal:"പൂച്ച / Cat"},
  {categoryMalayalam:"മൃഗങ്ങൾ",categoryEnglish:"Animals",normal:"കുതിര / Horse"},
  {categoryMalayalam:"മൃഗങ്ങൾ",categoryEnglish:"Animals",normal:"പശു / Cow"},
  {categoryMalayalam:"മൃഗങ്ങൾ",categoryEnglish:"Animals",normal:"മുയൽ / Rabbit"},
  {categoryMalayalam:"മൃഗങ്ങൾ",categoryEnglish:"Animals",normal:"കുരങ്ങ് / Monkey"},
  {categoryMalayalam:"മൃഗങ്ങൾ",categoryEnglish:"Animals",normal:"കരടി / Bear"},

  {categoryMalayalam:"സ്ഥലങ്ങൾ",categoryEnglish:"Places",normal:"സ്കൂൾ / School"},
  {categoryMalayalam:"സ്ഥലങ്ങൾ",categoryEnglish:"Places",normal:"കോളേജ് / College"},
  {categoryMalayalam:"സ്ഥലങ്ങൾ",categoryEnglish:"Places",normal:"ആശുപത്രി / Hospital"},
  {categoryMalayalam:"സ്ഥലങ്ങൾ",categoryEnglish:"Places",normal:"കടപ്പുറം / Beach"},
  {categoryMalayalam:"സ്ഥലങ്ങൾ",categoryEnglish:"Places",normal:"മല / Mountain"},
  {categoryMalayalam:"സ്ഥലങ്ങൾ",categoryEnglish:"Places",normal:"പാർക്ക് / Park"},
  {categoryMalayalam:"സ്ഥലങ്ങൾ",categoryEnglish:"Places",normal:"ലൈബ്രറി / Library"},
  {categoryMalayalam:"സ്ഥലങ്ങൾ",categoryEnglish:"Places",normal:"മാൾ / Mall"},
  {categoryMalayalam:"സ്ഥലങ്ങൾ",categoryEnglish:"Places",normal:"വിമാനത്താവളം / Airport"},
  {categoryMalayalam:"സ്ഥലങ്ങൾ",categoryEnglish:"Places",normal:"റെയിൽവേ സ്റ്റേഷൻ / Railway Station"},

  {categoryMalayalam:"ജോലി",categoryEnglish:"Jobs",normal:"ഡോക്ടർ / Doctor"},
  {categoryMalayalam:"ജോലി",categoryEnglish:"Jobs",normal:"നഴ്‌സ് / Nurse"},
  {categoryMalayalam:"ജോലി",categoryEnglish:"Jobs",normal:"ടീച്ചർ / Teacher"},
  {categoryMalayalam:"ജോലി",categoryEnglish:"Jobs",normal:"പോലീസ് / Police"},
  {categoryMalayalam:"ജോലി",categoryEnglish:"Jobs",normal:"എഞ്ചിനീയർ / Engineer"},
  {categoryMalayalam:"ജോലി",categoryEnglish:"Jobs",normal:"വക്കീൽ / Lawyer"},
  {categoryMalayalam:"ജോലി",categoryEnglish:"Jobs",normal:"പൈലറ്റ് / Pilot"},
  {categoryMalayalam:"ജോലി",categoryEnglish:"Jobs",normal:"ഷെഫ് / Chef"},
  {categoryMalayalam:"ജോലി",categoryEnglish:"Jobs",normal:"ഡ്രൈവർ / Driver"},
  {categoryMalayalam:"ജോലി",categoryEnglish:"Jobs",normal:"കർഷകൻ / Farmer"},

  {categoryMalayalam:"കായികം",categoryEnglish:"Sports",normal:"ഫുട്ബോൾ / Football"},
  {categoryMalayalam:"കായികം",categoryEnglish:"Sports",normal:"ക്രിക്കറ്റ് / Cricket"},
  {categoryMalayalam:"കായികം",categoryEnglish:"Sports",normal:"വോളിബോൾ / Volleyball"},
  {categoryMalayalam:"കായികം",categoryEnglish:"Sports",normal:"ബാഡ്മിന്റൺ / Badminton"},
  {categoryMalayalam:"കായികം",categoryEnglish:"Sports",normal:"ടെന്നീസ് / Tennis"},
  {categoryMalayalam:"കായികം",categoryEnglish:"Sports",normal:"ചെസ് / Chess"},
  {categoryMalayalam:"കായികം",categoryEnglish:"Sports",normal:"കരം / Carrom"},
  {categoryMalayalam:"കായികം",categoryEnglish:"Sports",normal:"നീന്തൽ / Swimming"},
  {categoryMalayalam:"കായികം",categoryEnglish:"Sports",normal:"കബഡി / Kabaddi"},
  {categoryMalayalam:"കായികം",categoryEnglish:"Sports",normal:"ഓട്ടം / Running"},

  {categoryMalayalam:"ടെക്നോളജി",categoryEnglish:"Technology",normal:"മൊബൈൽ / Mobile"},
  {categoryMalayalam:"ടെക്നോളജി",categoryEnglish:"Technology",normal:"ലാപ്ടോപ്പ് / Laptop"},
  {categoryMalayalam:"ടെക്നോളജി",categoryEnglish:"Technology",normal:"കീബോർഡ് / Keyboard"},
  {categoryMalayalam:"ടെക്നോളജി",categoryEnglish:"Technology",normal:"മൗസ് / Mouse"},
  {categoryMalayalam:"ടെക്നോളജി",categoryEnglish:"Technology",normal:"പ്രിന്റർ / Printer"},
  {categoryMalayalam:"ടെക്നോളജി",categoryEnglish:"Technology",normal:"വൈഫൈ / WiFi"},
  {categoryMalayalam:"ടെക്നോളജി",categoryEnglish:"Technology",normal:"ബ്ലൂടൂത്ത് / Bluetooth"},
  {categoryMalayalam:"ടെക്നോളജി",categoryEnglish:"Technology",normal:"യൂട്യൂബ് / YouTube"},
  {categoryMalayalam:"ടെക്നോളജി",categoryEnglish:"Technology",normal:"വാട്സ്ആപ്പ് / WhatsApp"},
  {categoryMalayalam:"ടെക്നോളജി",categoryEnglish:"Technology",normal:"ഗൂഗിൾ / Google"}
];
